"""added actual_revision for Redress Kit

Revision ID: 2032e2e77320
Revises: 8ce1245fcb55
Create Date: 2025-04-11 12:55:24.541475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2032e2e77320'
down_revision: Union[str, None] = '8ce1245fcb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redress_kit', sa.Column('actual_revision', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redress_kit', 'actual_revision')
    # ### end Alembic commands ###
