"""update redress kit consist model

Revision ID: 2564137c66f6
Revises: aec662cd0205
Create Date: 2025-04-21 12:35:40.268959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2564137c66f6'
down_revision: Union[str, None] = 'aec662cd0205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('redress_kit_consist_redress_kit_id_fkey', 'redress_kit_consist', type_='foreignkey')
    op.create_foreign_key(None, 'redress_kit_consist', 'item', ['redress_kit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'redress_kit_consist', type_='foreignkey')
    op.create_foreign_key('redress_kit_consist_redress_kit_id_fkey', 'redress_kit_consist', 'redress_kit', ['redress_kit_id'], ['id'])
    # ### end Alembic commands ###
