"""was added quantity to RedressKitConsist

Revision ID: 35cdb83385e7
Revises: d131d159a6d1
Create Date: 2025-04-10 15:26:58.662857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cdb83385e7'
down_revision: Union[str, None] = 'd131d159a6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redress_kit_consist', sa.Column('quantity', sa.Float(), nullable=False, comment='Количество'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redress_kit_consist', 'quantity')
    # ### end Alembic commands ###
