"""unique name for item added

Revision ID: 46b5565fcd60
Revises: d74467c3d7ae
Create Date: 2025-02-25 13:09:15.582281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b5565fcd60'
down_revision: Union[str, None] = 'd74467c3d7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    # ### end Alembic commands ###
