"""Add relation category / item

Revision ID: 5b3f6c981778
Revises: 667e36061c2c
Create Date: 2025-03-03 21:04:05.826769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3f6c981778'
down_revision: Union[str, None] = '667e36061c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', sa.UUID(), nullable=True))
    op.drop_constraint('item_category_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    op.drop_column('item', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_category_fkey', 'item', 'category', ['category'], ['id'])
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###
