"""added status

Revision ID: 8207b6654973
Revises: 870d876fc86b
Create Date: 2025-05-04 22:52:16.208407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8207b6654973'
down_revision: Union[str, None] = '870d876fc86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_equipment_id_fkey', 'asset', type_='foreignkey')
    op.create_foreign_key(None, 'asset', 'item', ['equipment_id'], ['id'])
    op.alter_column('item', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('ix_items_is_active', 'item', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_is_active', table_name='item')
    op.alter_column('item', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.create_foreign_key('asset_equipment_id_fkey', 'asset', 'equipment', ['equipment_id'], ['id'])
    # ### end Alembic commands ###
