"""change type of revision from Redress kit consist

Revision ID: 8ce1245fcb55
Revises: 35cdb83385e7
Create Date: 2025-04-11 07:47:48.296752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce1245fcb55'
down_revision: Union[str, None] = '35cdb83385e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'redress_kit', 'service_level', ['service_level'], ['id'])
    op.alter_column('redress_kit_consist', 'revision',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_comment='Версия набора ЗИП',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('redress_kit_consist', 'revision',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_comment='Версия набора ЗИП',
               existing_nullable=False)
    op.drop_constraint(None, 'redress_kit', type_='foreignkey')
    # ### end Alembic commands ###
