"""redress system update

Revision ID: 9f7283091bce
Revises: 1021943cc70e
Create Date: 2025-05-10 21:30:41.810542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f7283091bce'
down_revision: Union[str, None] = '1021943cc70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'asset',
        'Таблица с оборудованием (активами)',
        existing_comment=None,
        schema=None
    )
    op.add_column('checklist_steps', sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_table_comment(
        'checklist_steps',
        'Таблица с пунктами, необходимыми для выполнения сервиса',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'checklist_templates',
        'Таблица с шаблонами сервиса оборудования',
        existing_comment=None,
        schema=None
    )
    op.add_column('redress_equipment', sa.Column('tag', sa.UUID(), nullable=False))
    op.add_column('redress_equipment', sa.Column('completed_to', sa.String(length=32), nullable=False))
    op.alter_column('redress_equipment', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('redress_equipment', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'redress_equipment', ['completed_to'])
    op.create_foreign_key(None, 'redress_equipment', 'statuses', ['tag'], ['id'])
    op.create_table_comment(
        'redress_equipment',
        'Таблица с оборудованием после обслуживания',
        existing_comment=None,
        schema=None
    )
    op.alter_column('redress_steps', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table_comment(
        'redress_steps',
        'Таблица с ответами пользователей на шаги сервиса оборудования',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'template_equipment',
        'Дополнительная таблица шаблон - шаг',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'template_steps',
        'Дополнительная таблица шаблон - шаг',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'template_steps',
        existing_comment='Дополнительная таблица шаблон - шаг',
        schema=None
    )
    op.drop_table_comment(
        'template_equipment',
        existing_comment='Дополнительная таблица шаблон - шаг',
        schema=None
    )
    op.drop_table_comment(
        'redress_steps',
        existing_comment='Таблица с ответами пользователей на шаги сервиса оборудования',
        schema=None
    )
    op.alter_column('redress_steps', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table_comment(
        'redress_equipment',
        existing_comment='Таблица с оборудованием после обслуживания',
        schema=None
    )
    op.drop_constraint(None, 'redress_equipment', type_='foreignkey')
    op.drop_constraint(None, 'redress_equipment', type_='unique')
    op.alter_column('redress_equipment', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('redress_equipment', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('redress_equipment', 'completed_to')
    op.drop_column('redress_equipment', 'tag')
    op.drop_table_comment(
        'checklist_templates',
        existing_comment='Таблица с шаблонами сервиса оборудования',
        schema=None
    )
    op.drop_table_comment(
        'checklist_steps',
        existing_comment='Таблица с пунктами, необходимыми для выполнения сервиса',
        schema=None
    )
    op.drop_column('checklist_steps', 'fields')
    op.drop_table_comment(
        'asset',
        existing_comment='Таблица с оборудованием (активами)',
        schema=None
    )
    # ### end Alembic commands ###
