"""upgrade redress kit model

Revision ID: aec662cd0205
Revises: 6ac430e62ac3
Create Date: 2025-04-21 07:45:58.677887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec662cd0205'
down_revision: Union[str, None] = '6ac430e62ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'description')
    op.add_column('redress_kit', sa.Column('redress_kit', sa.UUID(), nullable=False))
    op.alter_column('redress_kit', 'actual_revision',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_foreign_key(None, 'redress_kit', 'item', ['redress_kit'], ['id'])
    op.drop_column('redress_kit', 'name')
    op.drop_column('redress_kit', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redress_kit', sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('redress_kit', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'redress_kit', type_='foreignkey')
    op.alter_column('redress_kit', 'actual_revision',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('redress_kit', 'redress_kit')
    op.add_column('groups', sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
