"""change equipment table

Revision ID: b3cc7aacd6d7
Revises: 7724a69798df
Create Date: 2025-03-27 20:30:03.287767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cc7aacd6d7'
down_revision: Union[str, None] = '7724a69798df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('part_number', sa.String(length=32), nullable=False))
    op.add_column('equipment', sa.Column('description', sa.String(length=256), nullable=True))
    op.drop_constraint('equipment_part_id_fkey', 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'part_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('equipment_part_id_fkey', 'equipment', 'part', ['part_id'], ['id'])
    op.drop_column('equipment', 'description')
    op.drop_column('equipment', 'part_number')
    # ### end Alembic commands ###
