"""update redress equipment table - comment - unique = false

Revision ID: c5f03a1065e6
Revises: 9de2bd749614
Create Date: 2025-05-20 13:05:58.239385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f03a1065e6'
down_revision: Union[str, None] = '9de2bd749614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('redress_equipment_comment_key', 'redress_equipment', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('redress_equipment_comment_key', 'redress_equipment', ['comment'])
    # ### end Alembic commands ###
