"""change Service equipment, User

Revision ID: db4cb4226df2
Revises: a76b5ff7f436
Create Date: 2025-03-31 22:32:48.008919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4cb4226df2'
down_revision: Union[str, None] = 'a76b5ff7f436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_equipment', sa.Column('id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'template_equipment', ['id'])
    op.add_column('users', sa.Column('alias', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_alias'), 'users', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_alias'), table_name='users')
    op.drop_column('users', 'alias')
    op.drop_constraint(None, 'template_equipment', type_='unique')
    op.drop_column('template_equipment', 'id')
    # ### end Alembic commands ###
